### ISSUE TITLE
크롬드라이버가 작동하지 않습니다

### ISSUE THREAD

**Issue by LeePC** [taehwakkwon/papago-translator#1]
(Session info: headless chrome=91.0.4472.114) 자꾸 이에러가 발생합니다 고쳐주실수 있으신가요??

Traceback (most recent call last):
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 180, in <module>
    translator.translate()
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 70, in translate
    pool.starmap(self._translate, zip(self.parts, repeat(self.translated)))
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#sourceEditArea textarea"}
  (Session info: headless chrome=91.0.4472.114)

참고로 윈도우 기반으로 작동시켰습니다
파이썬은 물론 다설치하고 모듈까지 다 설치해보고 chromedriver 까지 설치해보고 테스트한뒤 오류내용 보내드린겁니다

**Comment by taehwakkwon** [comment]
크롬 드라이버 버젼이 맞지않아 발생하는 오류라 생각됩니다. papago_translator.py의 options.add_argument("user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.3538.102 Safari/537.36") 부분을 LeePC님이 설치한 크롬 드라이버와 환경에 맞게 수정해주면 될듯 합니다! 저도 윈도우에서는 따로 테스트를 진행해보지 않아 죄송합니다!
