### ISSUE TITLE
역시 재확인해봐도 에러가 발생합니다

### ISSUE THREAD

**Issue by LeePC** [taehwakkwon/papago-translator#2]
$ python papago_translator.py --text_file english.txt --complete_file translated.json --sk en --tk kr
0it [00:19, ?it/s]
english.txt loaded
You have left 106
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 101, in _translate
    result = self.en2kr(sentence, driver, time_delay)
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 53, in en2kr
    input_box = driver.find_element_by_css_selector('#sourceEditArea textarea')
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#sourceEditArea textarea"}
  (Session info: headless chrome=91.0.4472.124)

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 180, in <module>
    translator.translate()
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 70, in translate
    pool.starmap(self._translate, zip(self.parts, repeat(self.translated)))
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#sourceEditArea textarea"}
  (Session info: headless chrome=91.0.4472.124)

driver initialized

맨 위에 명령어를 입력했습니다만 크롬버젼이 문제인지는 모르겠으나 에러가 발생합니다

**Comment by taehwakkwon** [comment]
혹시 papagoe_translatro.py의 55 line의 '#sourceEditArea textarea' 를 'txtSource' 로 바꾼 뒤 실행시켜 보시겠어요?

**Comment by taehwakkwon** [comment]
제 윈도우 환경에서 확인해본 결과 잘 작동하는데.. 

https://hello-bryan.tistory.com/193

다음 글을 참고해보시면 도움이 될것 같습니다!

**Comment by LeePC** [comment]
python papago_translator.py --text_file english.txt --complete_file translated.json --sk en --tk kr --path 'C:\Users\akrrk\Downloads\papago-translator-master\chromedriver.exe'
0it [00:19, ?it/s]
translated.json loaded
english.txt loaded
You got file of translated.json
0 lines translated
You have left 106 of total 106
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 101, in _translate
    result = self.en2kr(sentence, driver, time_delay)
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 53, in en2kr
    input_box = driver.find_element_by_css_selector('#sourceEditArea textarea')
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#sourceEditArea textarea"}
  (Session info: headless chrome=91.0.4472.124)

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 180, in <module>
    translator.translate()
  File "C:\Users\akrrk\Downloads\papago-translator-master\papago_translator.py", line 70, in translate
    pool.starmap(self._translate, zip(self.parts, repeat(self.translated)))
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\akrrk\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#sourceEditArea textarea"}
  (Session info: headless chrome=91.0.4472.124)

driver initialized

그쪽말대로 했지만 작동하지 않습니다
Python 버젼을 뭘로해야되는지 말씀좀 부탁드립니다

**Comment by LeePC** [comment]
저기 텍스트를 번역하면 json으로 출력되서 나올텐데 이거를 줄수 맞춰서 번역된것만 출력할순 없는건가요??
어떤 게임을 영어로 된걸 한글로 번역되는걸 찾고있긴한데
쯔꾸르 기반은 일본어번역기밖에 없더라구요 그래서 txt를 번역하면 그대로 번역해서 그대로 줄칸 똑같이 번역되서 나오는걸 찾고있습니다만
제가 github사이트를 자주검색하다보니 여기 소스파일이 많이 끌리더라구요
일단 번역해야될 파일이 이건데....
[System_Term.txt](https://github.com/taehwakkwon/papago-translator/files/6751667/System_Term.txt)
번호 건들지않고 옆에 있는 영어들을 번역하기만 해주는걸 찾고있습니다만
만들어주실순 없나요??

**Comment by taehwakkwon** [comment]
제가 직접 해드리긴 어려울듯 합니다 :) 제가 올린 코드를 활용해 번역하고, 문자열 처리를 통해 원하시는 파일을 만드실 수 있을겁니다! 감사합니다😁
